//Cabeçalho
void desenhaMinhaCena();
void drawPlacar(spriteScore objeto);
void drawObject(spriteObject objeto);
void drawObjectA(spriteOb_Animado_s objeto);
void addPoint(int pontuador);
void addSet(int pontuador, int tipoJogo);
void trocarJogadores();
void resetAll();
void resetBall();
void resetBar();
void resetPont();
void resetSet();
void moveBall();
void moveBar();
GLuint loadTexture(const char* arquivo);
void teclaPressionada(unsigned char key, int x, int y);
void teclaSegurada(unsigned char key, int x, int y);
void mouseClick(int botao, int estado, int x, int y);
void mouseMove(int x, int y);
void redimensionada(int width, int height);
void refresh(int delay);
void setup();
void trocarPosicoesPlacares();
void main(int argc, char** argv);
int vencedorMomento();
void posAtualEstrela();
void winner(int player);
void Switch();
void matchPoint(int player);
void setPoint(int player);
void rebatida(int player);
void sleep_bola(double segundos);
double bola_dormindo();
void move_kamek();
void move_mario();
void tempo_switch(double segundos);
double switch_rodando();
void reseta_cores();
void sleep(int segundos);
void move_wallpaper_direita();
void move_wallpaper_esquerda();
void faseAtual();
void comecaMusica(char const nome[40], int loop);
void paraMusica(void);